/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Allwinner A83t MIPI CSI-2 register description
 * Copyright Kévin L'hôpital (C) 2020
 */

#ifndef __SUN8I_A83T_MIPI_CSI2_REG_H__
#define __SUN8I_A83T_MIPI_CSI2_REG_H__


#define MIPI_CSI2_OFFSET				0x1000

#define MIPI_CSI2_VERSION_REG				(MIPI_CSI2_OFFSET + 0x000)
#define MIPI_CSI2_CTRL_REG				(MIPI_CSI2_OFFSET + 0x004)
#define MIPI_CSI2_CTRL_REG_RSTN				BIT(31)

#define MIPI_CSI2_RX_PKT_NUM_REG			(MIPI_CSI2_OFFSET + 0x008)
#define MIPI_CSI2_RSVD0_REG				(MIPI_CSI2_OFFSET + 0x00c)

#define MIPI_CSI2_RSVD1_REG				(MIPI_CSI2_OFFSET + 0x018)
/* Value found in the BSP and need to be present but it is not describe in the
 * datasheet.
 */
#define HW_LOCK_REGISTER_VALUE_1			0xb8c8a30c
#define MIPI_CSI2_RSVD2_REG				(MIPI_CSI2_OFFSET + 0x01c)
/* Value found in the BSP and need to be present but it is not describe in the
 * datasheet.
 */
#define HW_LOCK_REGISTER_VALUE_2			0xb8df8ad7

#define MIPI_CSI2_INT_STA0_REG				(MIPI_CSI2_OFFSET + 0x020)
#define MIPI_CSI2_INT_STA0_REG_ECC_ERR_DBL              BIT(28)
#define MIPI_CSI2_INT_STA0_REG_LINE_CKSM_ERR_VC3        BIT(27)
#define MIPI_CSI2_INT_STA0_REG_LINE_CKSM_ERR_VC2        BIT(26)
#define MIPI_CSI2_INT_STA0_REG_LINE_CKSM_ERR_VC1        BIT(25)
#define MIPI_CSI2_INT_STA0_REG_LINE_CKSM_ERR_VC0        BIT(24)
#define MIPI_CSI2_INT_STA0_REG_LINE_SEQ_ERR_DT3         BIT(23)
#define MIPI_CSI2_INT_STA0_REG_LINE_SEQ_ERR_DT2         BIT(22)
#define MIPI_CSI2_INT_STA0_REG_LINE_SEQ_ERR_DT1         BIT(21)
#define MIPI_CSI2_INT_STA0_REG_LINE_SEQ_ERR_DT0         BIT(20)
#define MIPI_CSI2_INT_STA0_REG_LS_LE_ERR_DT3            BIT(19)
#define MIPI_CSI2_INT_STA0_REG_LS_LE_ERR_DT2            BIT(18)
#define MIPI_CSI2_INT_STA0_REG_LS_LE_ERR_DT1            BIT(17)
#define MIPI_CSI2_INT_STA0_REG_LS_LE_ERR_DT0            BIT(16)
#define MIPI_CSI2_INT_STA0_REG_CRC_ERR_VC3              BIT(15)
#define MIPI_CSI2_INT_STA0_REG_CRC_ERR_VC2              BIT(14)
#define MIPI_CSI2_INT_STA0_REG_CRC_ERR_VC1              BIT(13)
#define MIPI_CSI2_INT_STA0_REG_CRC_ERR_VC0              BIT(12)
#define MIPI_CSI2_INT_STA0_REG_FRM_SEQ_ERR_VC3          BIT(11)
#define MIPI_CSI2_INT_STA0_REG_FRM_SEQ_ERR_VC2          BIT(10)
#define MIPI_CSI2_INT_STA0_REG_FRM_SEQ_ERR_VC1          BIT(9)
#define MIPI_CSI2_INT_STA0_REG_FRM_SEQ_ERR_VC0          BIT(8)
#define MIPI_CSI2_INT_STA0_REG_FS_FE_ERR_VC3            BIT(7)
#define MIPI_CSI2_INT_STA0_REG_FS_FE_ERR_VC2            BIT(6)
#define MIPI_CSI2_INT_STA0_REG_FS_FE_ERR_VC1            BIT(5)
#define MIPI_CSI2_INT_STA0_REG_FS_FE_ERR_VC0            BIT(4)
#define MIPI_CSI2_INT_STA0_REG_SOT_SYNC_ERR_3           BIT(3)
#define MIPI_CSI2_INT_STA0_REG_SOT_SYNC_ERR_2           BIT(2)
#define MIPI_CSI2_INT_STA0_REG_SOT_SYNC_ERR_1           BIT(1)
#define MIPI_CSI2_INT_STA0_REG_SOT_SYNC_ERR_0		BIT(0)

#define MIPI_CSI2_INT_STA1_REG				(MIPI_CSI2_OFFSET + 0x024)
#define MIPI_CSI2_INT_STA1_REG_LINE_SEQ_ERR_DT7         BIT(23)
#define MIPI_CSI2_INT_STA1_REG_LINE_SEQ_ERR_DT6         BIT(22)
#define MIPI_CSI2_INT_STA1_REG_LINE_SEQ_ERR_DT5         BIT(21)
#define MIPI_CSI2_INT_STA1_REG_LINE_SEQ_ERR_DT4         BIT(20)
#define MIPI_CSI2_INT_STA1_REG_LS_LE_ERR_DT7            BIT(19)
#define MIPI_CSI2_INT_STA1_REG_LS_LE_ERR_DT6            BIT(18)
#define MIPI_CSI2_INT_STA1_REG_LS_LE_ERR_DT5            BIT(17)
#define MIPI_CSI2_INT_STA1_REG_LS_LE_ERR_DT4            BIT(16)
#define MIPI_CSI2_INT_STA1_REG_DT_ERR_VC3               BIT(15)
#define MIPI_CSI2_INT_STA1_REG_DT_ERR_VC2               BIT(14)
#define MIPI_CSI2_INT_STA1_REG_DT_ERR_VC1               BIT(13)
#define MIPI_CSI2_INT_STA1_REG_DT_ERR_VC0               BIT(12)
#define MIPI_CSI2_INT_STA1_REG_ECC_ERR1_VC3             BIT(11)
#define MIPI_CSI2_INT_STA1_REG_ECC_ERR1_VC2             BIT(10)
#define MIPI_CSI2_INT_STA1_REG_ECC_ERR1_VC1             BIT(9)
#define MIPI_CSI2_INT_STA1_REG_ECC_ERR1_VC0             BIT(8)
#define MIPI_CSI2_INT_STA1_REG_SOT_ERR_3                BIT(7)
#define MIPI_CSI2_INT_STA1_REG_SOT_ERR_2                BIT(6)
#define MIPI_CSI2_INT_STA1_REG_SOT_ERR_1                BIT(5)
#define MIPI_CSI2_INT_STA1_REG_SOT_ERR_0                BIT(4)
#define MIPI_CSI2_INT_STA1_REG_ESC_ENTRY_ERR_3          BIT(3)
#define MIPI_CSI2_INT_STA1_REG_ESC_ENTRY_ERR_2          BIT(2)
#define MIPI_CSI2_INT_STA1_REG_ESC_ENTRY_ERR_1          BIT(1)
#define MIPI_CSI2_INT_STA1_REG_ESC_ENTRY_ERR_0		BIT(0)

#define MIPI_CSI2_INT_MSK0_REG				(MIPI_CSI2_OFFSET + 0x028)
#define MIPI_CSI2_INT_MSK0_REG_ECC_ERR_DBL_MSK          BIT(28)
#define MIPI_CSI2_INT_MSK0_REG_CKSM_ERR_VC3_MSK         BIT(27)
#define MIPI_CSI2_INT_MSK0_REG_CKSM_ERR_VC2_MSK         BIT(26)
#define MIPI_CSI2_INT_MSK0_REG_CKSM_ERR_VC1_MSK         BIT(25)
#define MIPI_CSI2_INT_MSK0_REG_CKSM_ERR_VC0_MSK         BIT(24)
#define MIPI_CSI2_INT_MSK0_REG_LINE_SEQ_ERR_DT3_MSK     BIT(23)
#define MIPI_CSI2_INT_MSK0_REG_LINE_SEQ_ERR_DT2_MSK     BIT(22)
#define MIPI_CSI2_INT_MSK0_REG_LINE_SEQ_ERR_DT1_MSK     BIT(21)
#define MIPI_CSI2_INT_MSK0_REG_LINE_SEQ_ERR_DT0_MSK     BIT(20)
#define MIPI_CSI2_INT_MSK0_REG_LS_LE_ERR_DT3_MSK        BIT(19)
#define MIPI_CSI2_INT_MSK0_REG_LS_LE_ERR_DT2_MSK        BIT(18)
#define MIPI_CSI2_INT_MSK0_REG_LS_LE_ERR_DT1_MSK        BIT(17)
#define MIPI_CSI2_INT_MSK0_REG_LS_LE_ERR_DT0_MSK        BIT(16)
#define MIPI_CSI2_INT_MSK0_REG_CRC_ERR_VC3_MSK          BIT(15)
#define MIPI_CSI2_INT_MSK0_REG_CRC_ERR_VC2_MSK          BIT(14)
#define MIPI_CSI2_INT_MSK0_REG_CRC_ERR_VC1_MSK          BIT(13)
#define MIPI_CSI2_INT_MSK0_REG_CRC_ERR_VC0_MSK          BIT(12)
#define MIPI_CSI2_INT_MSK0_REG_FRM_SEQ_ERR_VC3_MSK      BIT(11)
#define MIPI_CSI2_INT_MSK0_REG_FRM_SEQ_ERR_VC2_MSK      BIT(10)
#define MIPI_CSI2_INT_MSK0_REG_FRM_SEQ_ERR_VC1_MSK      BIT(9)
#define MIPI_CSI2_INT_MSK0_REG_FRM_SEQ_ERR_VC0_MSK      BIT(8)
#define MIPI_CSI2_INT_MSK0_REG_FS_FE_ERR_VC3_MSK        BIT(7)
#define MIPI_CSI2_INT_MSK0_REG_FS_FE_ERR_VC2_MSK        BIT(6)
#define MIPI_CSI2_INT_MSK0_REG_FS_FE_ERR_VC1_MSK        BIT(5)
#define MIPI_CSI2_INT_MSK0_REG_FS_FE_ERR_VC0_MSK        BIT(4)
#define MIPI_CSI2_INT_MSK0_REG_SOT_SYNC_ERR_3_MSK       BIT(3)
#define MIPI_CSI2_INT_MSK0_REG_SOT_SYNC_ERR_2_MSK       BIT(2)
#define MIPI_CSI2_INT_MSK0_REG_SOT_SYNC_ERR_1_MSK       BIT(1)
#define MIPI_CSI2_INT_MSK0_REG_SOT_SYNC_ERR_0_MSK	BIT(0)

#define MIPI_CSI2_INT_MSK1_REG				(MIPI_CSI2_OFFSET + 0x02c)
#define MIPI_CSI2_INT_MSK1_REG_DT_ERR_VC3_MSK           BIT(15)
#define MIPI_CSI2_INT_MSK1_REG_DT_ERR_VC2_MSK           BIT(14)
#define MIPI_CSI2_INT_MSK1_REG_DT_ERR_VC1_MSK           BIT(13)
#define MIPI_CSI2_INT_MSK1_REG_DT_ERR_VC0_MSK           BIT(12)
#define MIPI_CSI2_INT_MSK1_REG_ECC_ERR1_VC3_MSK         BIT(11)
#define MIPI_CSI2_INT_MSK1_REG_ECC_ERR1_VC2_MSK         BIT(10)
#define MIPI_CSI2_INT_MSK1_REG_ECC_ERR1_VC1_MSK         BIT(9)
#define MIPI_CSI2_INT_MSK1_REG_ECC_ERR1_VC0_MSK         BIT(8)
#define MIPI_CSI2_INT_MSK1_REG_SOT_ERR_3_MSK            BIT(7)
#define MIPI_CSI2_INT_MSK1_REG_SOT_ERR_2_MSK            BIT(6)
#define MIPI_CSI2_INT_MSK1_REG_SOT_ERR_1_MSK            BIT(5)
#define MIPI_CSI2_INT_MSK1_REG_SOT_ERR_0_MSK            BIT(4)
#define MIPI_CSI2_INT_MSK1_REG_ESC_ENTRY_ERR_3_MSK      BIT(3)
#define MIPI_CSI2_INT_MSK1_REG_ESC_ENTRY_ERR_2_MSK      BIT(2)
#define MIPI_CSI2_INT_MSK1_REG_ESC_ENTRY_ERR_1_MSK      BIT(1)
#define MIPI_CSI2_INT_MSK1_REG_ESC_ENTRY_ERR_0_MSK	BIT(0)

#define MIPI_CSI2_CFG_REG				(MIPI_CSI2_OFFSET + 0x100)
#define MIPI_CSI2_CFG_REG_SYNC_EN                       BIT(31)
#define MIPI_CSI2_CFG_REG_BYPASS_ECC_EN                 BIT(29)
#define MIPI_CSI2_CFG_REG_UNPKT_EN                      BIT(28)
#define MIPI_CSI2_CFG_REG_NONE_UNPKT_RX_MODE            BIT(27)
#define MIPI_CSI2_CFG_REG_YC_SWAB                       BIT(26)
#define MIPI_CSI2_CFG_REG_N_BYTE                        BIT(24)
#define MIPI_CSI2_CFG_REG_SYNC_DLY_CYCLE(v)             ((v) << 18)
#define MIPI_CSI2_CFG_REG_SYNC_DLY_CYCLE_MASK           GENMASK(22, 18)
#define MIPI_CSI2_CFG_REG_N_CHANNEL_MASK                GENMASK(17, 16)
#define MIPI_CSI2_CFG_REG_N_CHANNEL_SHIFT               16
#define MIPI_CSI2_CFG_REG_N_LANE_MASK                   GENMASK(5, 4)
#define MIPI_CSI2_CFG_REG_N_LANE_SHIFT			4

#define MIPI_CSI2_VCDT0_REG				(MIPI_CSI2_OFFSET + 0x104)
#define MIPI_CSI2_VCDT0_REG_DEFAULT                     0xc0804000
#define MIPI_CSI2_VCDT0_REG_CH3_VC_MASK                 GENMASK(31, 30)
#define MIPI_CSI2_VCDT0_REG_CH3_VC_SHIFT                30
#define MIPI_CSI2_VCDT0_REG_CH3_DT_MASK                 GENMASK(29, 24)
#define MIPI_CSI2_VCDT0_REG_CH3_DT_SHIFT                24
#define MIPI_CSI2_VCDT0_REG_CH2_VC_MASK                 GENMASK(23, 22)
#define MIPI_CSI2_VCDT0_REG_CH2_VC_SHIFT                22
#define MIPI_CSI2_VCDT0_REG_CH2_DT_MASK                 GENMASK(21, 16)
#define MIPI_CSI2_VCDT0_REG_CH2_DT_SHIFT                16
#define MIPI_CSI2_VCDT0_REG_CH1_VC_MASK                 GENMASK(15, 14)
#define MIPI_CSI2_VCDT0_REG_CH1_VC_SHIFT                14
#define MIPI_CSI2_VCDT0_REG_CH1_DT_MASK                 GENMASK(13, 8)
#define MIPI_CSI2_VCDT0_REG_CH1_DT_SHIFT                8
#define MIPI_CSI2_VCDT0_REG_CH0_VC_MASK                 GENMASK(7, 6)
#define MIPI_CSI2_VCDT0_REG_CH0_VC_SHIFT                6
#define MIPI_CSI2_VCDT0_REG_CH0_DT_MASK			GENMASK(5, 0)

#define MIPI_CSI2_VCDT1_REG				(MIPI_CSI2_OFFSET + 0x108)
#define MIPI_CSI2_VCDT1_REG_CH7_VC_MASK                 GENMASK(31, 30)
#define MIPI_CSI2_VCDT1_REG_CH7_DT_MASK                 GENMASK(29, 24)
#define MIPI_CSI2_VCDT1_REG_CH6_VC_MASK                 GENMASK(23, 22)
#define MIPI_CSI2_VCDT1_REG_CH6_DT_MASK                 GENMASK(21, 16)
#define MIPI_CSI2_VCDT1_REG_CH5_VC_MASK                 GENMASK(15, 14)
#define MIPI_CSI2_VCDT1_REG_CH5_DT_MASK                 GENMASK(13, 8)
#define MIPI_CSI2_VCDT1_REG_CH4_VC_MASK                 GENMASK(7, 6)
#define MIPI_CSI2_VCDT1_REG_CH4_DT_MASK			GENMASK(5, 0)

#endif /* __SUN8I_A83T_MIPI_CSI2_REG_H__ */
